# Site settings
title: "The Hive"
bye_message: "--"
baseurl: "/"
url: "https://markroxor.github.io"
disqus: markroxor

# Name of website
title: Mark's  Hive

# Short description of your site
description: ...

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
permalink: pretty
paginate: 3

plugins: [jekyll-paginate]
paginate_path: "/blog/page:num/"
# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
