# Site settings
title: "The Hive"
bye_message: "--"
baseurl: "/"
url: "https://markroxor.github.io"
disqus: markroxor

# Name of website
title: Mark's  Hive

# Short description of your site
description: ...

timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
permalink: pretty
paginate: 10
future: true

plugins: [jekyll-paginate]
paginate_path: "/blog/page:num/"
# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - schedule/node_modules
